baseURL: 'http://emmmali.github.io/portfolio/'
languageCode: 'en-us'
title: 'emma li'
theme: 'PaperMod'

menu:
  main:
    # - identifier: home
    #   name: Home
    #   url: /
    #   weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
    - identifier: experience
      name: Experience
      url: /experience
      weight: 30
    - identifier: blog
      name: Blog
      url: /blog
      weight: 40
    - identifier: search
      name: 🔎
      url: /search
      weight: 50

params:
  # theme
  # showToc: true
  # TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  hideMeta: false
  # hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "emma li"
    subtitle: "i'm emma and i'm a cs student @ rice university. i'm currently working as a data engineering / ml intern @ chevron and an ml researcher for education @ openstax. interested in data for social impact, machine learning and generative ai, cloud, and devops."
    imageUrl: "home/glass_orb.jpeg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  # hideDescriptionInList: false

  # cover image for posts
  # cover:
  #   hiddenInList: false # hide on list pages and home
  #   hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:el36@grice.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/emma-li-2021/"
    - name: "github"
      url: "https://github.com/emmmali"
    - name: "cv"
      url: "https://drive.google.com/file/d/160iEsqxkeFCEwki13O_CIEjI36_4kZPL/view?usp=sharing"

  # Custom Favicon
  assets:
        favicon: "https://thenounproject.com/api/private/icons/1919183/edit/?backgroundShape=SQUARE&backgroundShapeColor=%23000000&backgroundShapeOpacity=0&exportSize=752&flipX=false&flipY=false&foregroundColor=%23000000&foregroundOpacity=1&imageFormat=png&rotation=0"

  # Outputs for search
  outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary

  # Fuse options for search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  