baseURL: 'http://emmmali.github.io/portfolio/'
languageCode: 'en-us'
title: 'emma li'
theme: 'PaperMod'

# menu:
#   main:
#     - identifier: home
#       name: Home
#       url: /
#       weight: 10
#     - identifier: blog
#       name: Blog
#       url: /blog
#       weight: 20
#     - identifier: projects
#       name: Projects
#       url: /projects
#       weight: 30
#     - identifier: experience
#       name: Experience
#       url: /experience
#       weight: 40
#     - identifier: search
#       name: Search
#       url: /search
#       weight: 50

params:
  # theme
  # showToc: true
  # TocOpen: false
  # ShowBreadCrumbs: true
  # ShowCodeCopyButtons: true
  # hideMeta: false

  # for enchanced SEO
  # env: production

  # Home Page
  profileMode:
    enabled: true
    title: "emma li"
    subtitle: "i'm emma and i'm a cs student @ rice university. i'm currently working as a data engineering / ml intern @ chevron and an ml researcher for education @ openstax. interested in data for social impact, machine learning and generative ai, cloud, and devops."
    # imageUrl: "home/me.jpg"
    # imageWidth: 220
    # imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  # hideDescriptionInList: false

  # cover image for posts
  # cover:
  #   hiddenInList: false # hide on list pages and home
  #   hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:el36@grice.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/emma-li-2021/"
    - name: "github"
      url: "https://github.com/emmmali"
    - name: "cv"
      url: "https://docs.google.com/document/d/1ezt0rWbIithbnf9_nUdbhuZIpchvyO9J_eRcVVnSHLg/edit?usp=sharing"